export const SAMPLE_SHORT_URL = 'https://youtube.com/shorts/16f3qfDccKc'

const questionPrompts = [
  'Is gossip really a sin if the story is true?',
  'Can anger become sinful even when the reason is fair?',
  'Is skipping prayer once the same as rejecting God?',
  'Does envy count if I never act on it?',
  'Can entertainment slowly pull me away from holiness?',
  'Is it wrong to forgive someone but keep boundaries?',
  'Can pride hide inside good deeds?',
  'Is joking about sin harmless?',
  'What makes a habit spiritually dangerous?',
  'Can comparison become a form of ungratefulness?',
  'Is silence ever the wrong response?',
  'Can laziness show up in spiritual life?',
  'Is doubting the same thing as disbelief?',
  'Can ambition become idolatry?',
  'Is it sinful to be tempted?',
  'Can kindness be fake if I want approval?',
  'Does listening to cruel humor affect my heart?',
  'Is revenge sinful if it only happens in my thoughts?',
  'Can social media become a spiritual trap?',
  'Is impatience a small sin or a serious warning?',
  'Can I love God and still struggle with obedience?',
  'Is it wrong to avoid hard conversations?',
  'Can generosity be selfish?',
  'Is fear ever a lack of trust?',
  'Can judging others start as concern?',
  'Is wasting time a spiritual issue?',
  'Can success make me spiritually careless?',
  'Is pretending to be okay dishonest?',
  'Can curiosity lead into sin?',
  'Is it wrong to question a teaching?',
  'Can comfort become an idol?',
  'Does gratitude protect against sin?',
  'Is complaining always sinful?',
  'Can good intentions excuse bad actions?',
  'Is spiritual discipline meant to feel easy?',
  'Can repentance be real if I struggle again?',
]

const answerPrompts = [
  'Truth does not automatically make speech loving. A good check is whether the words protect dignity, seek healing, and belong in the conversation.',
  'Anger can point to something that matters, but it becomes dangerous when it starts demanding control, revenge, or permission to wound.',
  'One missed prayer is not the same as rejection. The better question is whether neglect is becoming a pattern you are no longer fighting.',
  'Envy is an interior warning light. Even without action, it can train the heart to resent someone else instead of receiving your own life with gratitude.',
  'Entertainment is not automatically harmful, but repeated exposure can normalize what your conscience used to notice. Pay attention to what it makes easier to excuse.',
  'Forgiveness releases revenge; it does not require pretending trust was never damaged. Wise boundaries can be part of loving truthfully.',
  'Pride can wear generous clothing. If the deed secretly needs applause to feel worthwhile, it may be time to return the motive to God.',
  'Jokes shape what a community treats as normal. Humor that makes sin look harmless can lower the guard before the choice arrives.',
  'A habit becomes spiritually dangerous when it trains desire, weakens freedom, and makes repentance feel increasingly distant.',
  'Comparison often turns attention away from gifts already given. Gratitude interrupts the habit of measuring your life by someone else’s portion.',
  'Silence can be wise, but it can also protect fear, comfort, or injustice. The test is whether silence serves love and truth.',
  'Laziness is not only about work. It can appear as refusing prayer, avoiding responsibility, or drifting when love asks for effort.',
  'Doubt is not disbelief by itself. Honest questions can become part of faith when they move toward truth instead of away from trust.',
  'Ambition becomes idolatry when success starts deciding your worth, your obedience, or what you are willing to sacrifice.',
  'Temptation is not the sin; consent is the turning point. The first pull is a place to ask for help, not a place to despair.',
  'A kind action can still need purification. Wanting approval is human, but love becomes freer when it does not depend on being seen.',
  'Repeated cruelty, even as comedy, can train the heart to enjoy contempt. What we laugh at can quietly educate what we tolerate.',
  'Imagined revenge can keep bitterness alive. Bringing those thoughts into prayer is often the first step toward real freedom.',
  'Social media becomes a trap when it feeds envy, lust, pride, rage, or distraction more than connection, truth, and charity.',
  'Impatience is common, but it reveals where control has replaced trust. Small moments can become practice for deeper peace.',
  'Yes. Love can be real while obedience is still maturing. The question is whether the struggle is being surrendered or defended.',
  'Avoiding a hard conversation can preserve peace for a moment while damaging truth for longer. Charity often needs courage.',
  'Generosity can be mixed with image, control, or pressure. The cleaner version gives freely and lets the gift belong to God.',
  'Fear is not automatically sin. It becomes spiritually harmful when it makes God seem smaller than the thing you are afraid of.',
  'Concern becomes judgment when it forgets humility, mercy, and your own need for grace.',
  'Time is part of stewardship. Rest is good, but wastefulness can become a way of avoiding love, service, or growth.',
  'Success can dull dependence if you start believing you are self-made. Gratitude keeps achievement from turning into spiritual sleep.',
  'Pretending can become dishonest when it blocks help or hides truth from people who have a right to know. Honesty can be gentle and still be real.',
  'Curiosity is good when ordered toward truth. It becomes risky when it seeks what weakens purity, peace, or obedience.',
  'Questioning can be faithful when it seeks understanding with humility. Cynicism is different because it often decides the answer before listening.',
  'Comfort becomes an idol when it has veto power over obedience. Real peace can ask for sacrifice.',
  'Gratitude changes attention. It makes the heart less hungry for resentment, comparison, and entitlement.',
  'Complaining is not always sinful, but it can become a habit of distrust. Lament brings pain to God; complaint often keeps it turned inward.',
  'Good intentions matter, but they do not erase harm. Love cares about both motive and fruit.',
  'Discipline often begins before emotion agrees. Steady practice can teach the heart what it does not yet feel.',
  'Repentance can be real even when healing takes time. Returning quickly, honestly, and humbly matters more than pretending the struggle vanished.',
]

export const defaultQuestions = questionPrompts.map((question, index) => ({
  id: index + 1,
  question,
  answer: answerPrompts[index],
  videoUrl: SAMPLE_SHORT_URL,
}))
